"""Compiler analyses."""

from .causality import (
    CausalityAnalysis,
    CausalityEdge,
    CausalityEdgeKind,
    CausalityGraph,
    ClockRelation,
    LogicalDependency,
    StateOrderError,
    analyze_causality,
    collect_state_reads,
    event_causality_graph,
    has_nonpositive_cycle,
    infer_commit_offset,
    periodic_causality_graph,
    state_read_occurrences,
)
from .latency import FACTORIO_LATENCY, TargetLatencyModel
from .physical_census import (
    AbstractPhysicalCensus,
    census_abstract_physical,
    format_abstract_physical_census,
)
from .state_timing import (
    ClockDomainTiming,
    EventClockTiming,
    RegisterTiming,
    StateReadTiming,
    StateTimingError,
    StateTimingPlan,
    UnsupportedClockCrossing,
    analyze_clocked_timing,
    analyze_normalized_state_timing,
    analyze_state_timing,
    earliest_scalar_phase,
    earliest_vector_phase,
    validate_event_throughput,
)

__all__ = [
    "AbstractPhysicalCensus",
    "CausalityAnalysis",
    "CausalityEdge",
    "CausalityEdgeKind",
    "CausalityGraph",
    "ClockDomainTiming",
    "ClockRelation",
    "FACTORIO_LATENCY",
    "EventClockTiming",
    "LogicalDependency",
    "RegisterTiming",
    "StateOrderError",
    "StateReadTiming",
    "StateTimingError",
    "StateTimingPlan",
    "TargetLatencyModel",
    "UnsupportedClockCrossing",
    "analyze_causality",
    "analyze_normalized_state_timing",
    "analyze_clocked_timing",
    "analyze_state_timing",
    "census_abstract_physical",
    "collect_state_reads",
    "earliest_scalar_phase",
    "earliest_vector_phase",
    "event_causality_graph",
    "format_abstract_physical_census",
    "has_nonpositive_cycle",
    "infer_commit_offset",
    "periodic_causality_graph",
    "state_read_occurrences",
    "validate_event_throughput",
]
