"""Public API for factorio-circuit-compiler."""

from .analysis.state_timing import ClockDomainTiming, StateTimingError, StateTimingPlan
from .compiler import (
    AbstractCompilationResult,
    CompilationResult,
    compile_abstract_circuit,
    compile_circuit,
)
from .events import (
    EventCausalityError,
    EventCompilationError,
    EventCrossingError,
    EventMaterializationError,
    EventScheduleError,
    EventThroughputError,
)
from .frontend import (
    AccumulatorReg,
    Circuit,
    CircuitBuildError,
    Expr,
    FreezeReg,
    Input,
    LogicalTime,
    SampleOnReference,
    ScalarEvent,
    SignalsExpr,
    SignalsInput,
    VectorEvent,
)
from .ir.physical import SignalId
from .simulate.events import (
    EventActivation,
    EventMaterializationPolicy,
    EventOccurrence,
    EventReaction,
    EventSchedule,
    EventSimulationResult,
    MaterializedEventTrace,
    SampleOnObservation,
    TimestampDomain,
    materialize_event_trace,
    simulate_events,
)
from .synthesis.placement import PlacementMetrics, PlacementOptions, placement_metrics

__all__ = [
    "AbstractCompilationResult",
    "AccumulatorReg",
    "Circuit",
    "CircuitBuildError",
    "ClockDomainTiming",
    "CompilationResult",
    "Expr",
    "EventCausalityError",
    "EventActivation",
    "EventCompilationError",
    "EventCrossingError",
    "EventOccurrence",
    "EventReaction",
    "EventSchedule",
    "EventScheduleError",
    "EventSimulationResult",
    "EventMaterializationError",
    "EventMaterializationPolicy",
    "EventThroughputError",
    "FreezeReg",
    "Input",
    "LogicalTime",
    "PlacementMetrics",
    "PlacementOptions",
    "SignalsExpr",
    "SignalsInput",
    "SampleOnReference",
    "ScalarEvent",
    "SignalId",
    "StateTimingError",
    "StateTimingPlan",
    "compile_abstract_circuit",
    "compile_circuit",
    "placement_metrics",
    "simulate_events",
    "materialize_event_trace",
    "MaterializedEventTrace",
    "SampleOnObservation",
    "TimestampDomain",
    "VectorEvent",
]
