"""Public API for factorio-circuit-compiler."""

from .analysis.state_timing import ClockDomainTiming, StateTimingError, StateTimingPlan
from .compiler import (
    AbstractPhysicalLoweringResult,
    CompilationResult,
    compile_circuit,
    lower_to_abstract_physical,
)
from .events import (
    EventCausalityError,
    EventCompilationError,
    EventCrossingError,
    EventMaterializationError,
    EventScheduleError,
    EventThroughputError,
)
from .frontend import (
    AccumulatorReg,
    Circuit,
    CircuitBuildError,
    Expr,
    FreezeReg,
    Input,
    LogicalTime,
    Oracle,
    SampleOnReference,
    ScalarEvent,
    SignalsExpr,
    SignalsInput,
    SignalsOracle,
    VectorEvent,
)
from .ir.output import (
    MaterializedReturnValue,
    OutputMaterialization,
    OutputMaterializationPolicy,
    output_materializations,
)
from .ir.physical import SignalId
from .oracles import (
    AnchoredPlacement,
    ExternalOracleProvider,
    FreePlacement,
    OracleBindingError,
    OraclePhysicalContext,
    OraclePortDisposition,
    OracleProvider,
    ScalarConstantOracleProvider,
    VectorConstantOracleProvider,
)
from .progress import CompileProgress, ProgressCallback
from .simulate.clocked_events import simulate_events
from .simulate.events import (
    EventActivation,
    EventMaterializationPolicy,
    EventOccurrence,
    EventReaction,
    EventSchedule,
    EventSimulationResult,
    MaterializedEventTrace,
    SampleOnObservation,
    TimestampDomain,
    materialize_event_trace,
)
from .simulate.oracle import simulate_stream_with_oracles
from .simulate.output_materialization import MaterializedOutputTrace, materialize_output_trace
from .synthesis.placement import PlacementMetrics, PlacementOptions, placement_metrics

__all__ = [
    "AbstractPhysicalLoweringResult",
    "AccumulatorReg",
    "AnchoredPlacement",
    "Circuit",
    "CircuitBuildError",
    "ClockDomainTiming",
    "CompilationResult",
    "CompileProgress",
    "Expr",
    "EventCausalityError",
    "EventActivation",
    "EventCompilationError",
    "EventCrossingError",
    "EventOccurrence",
    "EventReaction",
    "EventSchedule",
    "EventScheduleError",
    "EventSimulationResult",
    "EventMaterializationError",
    "EventMaterializationPolicy",
    "EventThroughputError",
    "ExternalOracleProvider",
    "FreePlacement",
    "FreezeReg",
    "Input",
    "LogicalTime",
    "MaterializedEventTrace",
    "MaterializedOutputTrace",
    "MaterializedReturnValue",
    "Oracle",
    "OracleBindingError",
    "OraclePhysicalContext",
    "OraclePortDisposition",
    "OracleProvider",
    "OutputMaterialization",
    "OutputMaterializationPolicy",
    "PlacementMetrics",
    "PlacementOptions",
    "ProgressCallback",
    "ScalarConstantOracleProvider",
    "SignalsExpr",
    "SignalsInput",
    "SignalsOracle",
    "SampleOnObservation",
    "SampleOnReference",
    "ScalarEvent",
    "SignalId",
    "StateTimingError",
    "StateTimingPlan",
    "TimestampDomain",
    "VectorConstantOracleProvider",
    "VectorEvent",
    "compile_circuit",
    "lower_to_abstract_physical",
    "materialize_event_trace",
    "materialize_output_trace",
    "output_materializations",
    "placement_metrics",
    "simulate_events",
    "simulate_stream_with_oracles",
]
